package com.sinosoft.entity;

public class FansinfoDto extends FansinfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_fansinfo.NICK_NAME
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_fansinfo.GENDER
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_fansinfo.REMARK_NAME
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    private String remarkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_fansinfo.ADDRESS
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_fansinfo.PICSRC
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    private String picsrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_fansinfo.SIGNATURE
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    private String signature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_fansinfo.GROUPID
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    private String groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_fansinfo.GROUPS
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    private String groups;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_fansinfo.NICK_NAME
     *
     * @return the value of wechat_fansinfo.NICK_NAME
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_fansinfo.NICK_NAME
     *
     * @param nickName the value for wechat_fansinfo.NICK_NAME
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_fansinfo.GENDER
     *
     * @return the value of wechat_fansinfo.GENDER
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_fansinfo.GENDER
     *
     * @param gender the value for wechat_fansinfo.GENDER
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_fansinfo.REMARK_NAME
     *
     * @return the value of wechat_fansinfo.REMARK_NAME
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    public String getRemarkName() {
        return remarkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_fansinfo.REMARK_NAME
     *
     * @param remarkName the value for wechat_fansinfo.REMARK_NAME
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    public void setRemarkName(String remarkName) {
        this.remarkName = remarkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_fansinfo.ADDRESS
     *
     * @return the value of wechat_fansinfo.ADDRESS
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_fansinfo.ADDRESS
     *
     * @param address the value for wechat_fansinfo.ADDRESS
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_fansinfo.PICSRC
     *
     * @return the value of wechat_fansinfo.PICSRC
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    public String getPicsrc() {
        return picsrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_fansinfo.PICSRC
     *
     * @param picsrc the value for wechat_fansinfo.PICSRC
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    public void setPicsrc(String picsrc) {
        this.picsrc = picsrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_fansinfo.SIGNATURE
     *
     * @return the value of wechat_fansinfo.SIGNATURE
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_fansinfo.SIGNATURE
     *
     * @param signature the value for wechat_fansinfo.SIGNATURE
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_fansinfo.GROUPID
     *
     * @return the value of wechat_fansinfo.GROUPID
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_fansinfo.GROUPID
     *
     * @param groupid the value for wechat_fansinfo.GROUPID
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_fansinfo.GROUPS
     *
     * @return the value of wechat_fansinfo.GROUPS
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    public String getGroups() {
        return groups;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_fansinfo.GROUPS
     *
     * @param groups the value for wechat_fansinfo.GROUPS
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    public void setGroups(String groups) {
        this.groups = groups;
    }
}