package com.sinosoft.entity;

public class ManuDto extends WechatManuKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_manu.NAME
     *
     * @mbggenerated Mon Nov 25 15:37:09 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_manu.TYPE
     *
     * @mbggenerated Mon Nov 25 15:37:09 CST 2013
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_manu.KEYURL
     *
     * @mbggenerated Mon Nov 25 15:37:09 CST 2013
     */
    private String keyurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_manu.NAME
     *
     * @return the value of wechat_manu.NAME
     *
     * @mbggenerated Mon Nov 25 15:37:09 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_manu.NAME
     *
     * @param name the value for wechat_manu.NAME
     *
     * @mbggenerated Mon Nov 25 15:37:09 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_manu.TYPE
     *
     * @return the value of wechat_manu.TYPE
     *
     * @mbggenerated Mon Nov 25 15:37:09 CST 2013
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_manu.TYPE
     *
     * @param type the value for wechat_manu.TYPE
     *
     * @mbggenerated Mon Nov 25 15:37:09 CST 2013
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_manu.KEYURL
     *
     * @return the value of wechat_manu.KEYURL
     *
     * @mbggenerated Mon Nov 25 15:37:09 CST 2013
     */
    public String getKeyurl() {
        return keyurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_manu.KEYURL
     *
     * @param keyurl the value for wechat_manu.KEYURL
     *
     * @mbggenerated Mon Nov 25 15:37:09 CST 2013
     */
    public void setKeyurl(String keyurl) {
        this.keyurl = keyurl;
    }
}