package com.sinosoft.entity;

public class MessageResponseDto extends MessageResponseKey{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_messageresponse.RESPONSETYPE
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
    private String responsetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_messageresponse.TITLE
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_messageresponse.CONTENT
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_messageresponse.PICTURE
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_messageresponse.LINKURL
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
    private String linkurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_messageresponse.RESPONSETYPE
     *
     * @return the value of wechat_messageresponse.RESPONSETYPE
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
public MessageResponseDto(){
    	
    }
    
	public MessageResponseDto(String userid,String keyword,
		String responsetype,String requesttype,String title,String content,String picture,String linkurl){
    	this.setUserid(userid);
    	this.setKeyword(keyword);
    	this.setRequesttype(requesttype);
    	
    	this.responsetype = responsetype;
    	this.title = title;
    	this.content = content;
    	this.picture = picture;
    	this.linkurl = linkurl;
    	
    }
    public String getResponsetype() {
        return responsetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_messageresponse.RESPONSETYPE
     *
     * @param responsetype the value for wechat_messageresponse.RESPONSETYPE
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
    public void setResponsetype(String responsetype) {
        this.responsetype = responsetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_messageresponse.TITLE
     *
     * @return the value of wechat_messageresponse.TITLE
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_messageresponse.TITLE
     *
     * @param title the value for wechat_messageresponse.TITLE
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_messageresponse.CONTENT
     *
     * @return the value of wechat_messageresponse.CONTENT
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_messageresponse.CONTENT
     *
     * @param content the value for wechat_messageresponse.CONTENT
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_messageresponse.PICTURE
     *
     * @return the value of wechat_messageresponse.PICTURE
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_messageresponse.PICTURE
     *
     * @param picture the value for wechat_messageresponse.PICTURE
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_messageresponse.LINKURL
     *
     * @return the value of wechat_messageresponse.LINKURL
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
    public String getLinkurl() {
        return linkurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_messageresponse.LINKURL
     *
     * @param linkurl the value for wechat_messageresponse.LINKURL
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
    public void setLinkurl(String linkurl) {
        this.linkurl = linkurl;
    }
}