package com.sinosoft.entity;

public class MessageResponseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_messageresponse.USERID
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_messageresponse.KEYWORD
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_messageresponse.REQUESTTYPE
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
    private String requesttype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_messageresponse.USERID
     *
     * @return the value of wechat_messageresponse.USERID
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_messageresponse.USERID
     *
     * @param userid the value for wechat_messageresponse.USERID
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_messageresponse.KEYWORD
     *
     * @return the value of wechat_messageresponse.KEYWORD
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_messageresponse.KEYWORD
     *
     * @param keyword the value for wechat_messageresponse.KEYWORD
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_messageresponse.REQUESTTYPE
     *
     * @return the value of wechat_messageresponse.REQUESTTYPE
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
    public String getRequesttype() {
        return requesttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_messageresponse.REQUESTTYPE
     *
     * @param requesttype the value for wechat_messageresponse.REQUESTTYPE
     *
     * @mbggenerated Wed Dec 25 10:07:19 CST 2013
     */
    public void setRequesttype(String requesttype) {
        this.requesttype = requesttype;
    }
    public MessageResponseKey(){
    	
    }
    public MessageResponseKey(String userid,String keyword,String requesttype){
    	this.userid = userid;
    	this.keyword = keyword;
    	this.requesttype=requesttype;
    }
}