package com.sinosoft.entity;

public class WechatManuKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_manu.USERID
     *
     * @mbggenerated Mon Nov 25 15:37:09 CST 2013
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_manu.POSITION
     *
     * @mbggenerated Mon Nov 25 15:37:09 CST 2013
     */
    private String position;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_manu.USERID
     *
     * @return the value of wechat_manu.USERID
     *
     * @mbggenerated Mon Nov 25 15:37:09 CST 2013
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_manu.USERID
     *
     * @param userid the value for wechat_manu.USERID
     *
     * @mbggenerated Mon Nov 25 15:37:09 CST 2013
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_manu.POSITION
     *
     * @return the value of wechat_manu.POSITION
     *
     * @mbggenerated Mon Nov 25 15:37:09 CST 2013
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_manu.POSITION
     *
     * @param position the value for wechat_manu.POSITION
     *
     * @mbggenerated Mon Nov 25 15:37:09 CST 2013
     */
    public void setPosition(String position) {
        this.position = position;
    }
}