package com.sinosoft.dao;

import java.util.List;

import com.sinosoft.entity.FansinfoDto;
import com.sinosoft.entity.FansinfoKey;


public interface FansinfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_fansinfo
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    int deleteByPrimaryKey(FansinfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_fansinfo
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    int insert(FansinfoDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_fansinfo
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    int insertSelective(FansinfoDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_fansinfo
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    FansinfoDto selectByPrimaryKey(FansinfoKey key);
    
    
    List<FansinfoDto> selectAll(String userid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_fansinfo
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    int updateByPrimaryKeySelective(FansinfoDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_fansinfo
     *
     * @mbggenerated Mon Dec 09 10:57:04 CST 2013
     */
    int updateByPrimaryKey(FansinfoDto record);
    
    int deleteByUserid(String userid);
}